const navigationConfig = [
  {
    id: "Main",
    title: "MAIN",
    type: "group",
    children: [
      {
        id: "trangchu",
        title: "Trang chủ",
        type: "item",
        icon: "apps",
        url: "/",
        exact: true,
      },
      {
        id: "taisan",
        title: "Tài sản",
        type: "collapse",
        icon: "source",
        badge: {
          title: "2",
          bg: "#525E8A",
          fg: "#FFFFFF",
        },
        children: [
          {
            id: "tscd",
            title: "Tài sản cố định",
            type: "item",
            url: "/pages/posts",
            exact: true,
          },
          {
            id: "ccdc",
            title: "Công cụ dụng cụ",
            type: "item",
            url: "/pages/posts/add-post",
            exact: true,
          },
        ],
      },
      {
        id: "vitri",
        title: "Vị trí",
        type: "item",
        icon: "location_on",
        url: "/pages/calendar",
        exact: true,
      },
      {
        id: "thanhly",
        title: "Thanh lý",
        type: "item",
        icon: "point_of_sale",
        url: "/pages/calendarx",
        exact: true,
      },
      {
        id: "nhansu",
        title: "Nhân sự",
        type: "item",
        icon: "people_alt",
        url: "/pages/calendars",
        exact: true,
      },
      {
        id: "bophan",
        title: "Bộ phận ",
        type: "item",
        icon: "apartment",
        url: "/pages/calendarxx",
        exact: true,
      },
    ],
  },

  {
    id: "dd",
    title: "FORM ĐÃ LÀM",
    type: "group",
    children: [
      {
        id: "organization",
        title: "Tổ chức",
        type: "item",
        icon: "apps",
        url: "/organization",
        exact: true,
      },
      {
        id: "calculationUnit",
        title: "Đơn vị tính",
        type: "item",
        icon: "apps",
        url: "/calculationUnit",
        exact: true,
      },
      {
        id: "group",
        title: "Nhóm Tài sản/CCDC",
        type: "item",
        icon: "apps",
        url: "/group",
        exact: true,
      },
      {
        id: "category",
        title: "Danh mục",
        type: "item",
        icon: "apps",
        url: "/category",
        exact: true,
      },
      {
        id: "AdditionalConfig",
        title: "Đợt bổ sung",
        type: "item",
        icon: "apps",
        url: "/additional",
        exact: true,
      },
      {
        id: "product",
        title: "Sản phẩm",
        type: "item",
        icon: "apps",
        url: "/product",
        exact: true,
      },
      {
        id: "campus",
        title: "Khuôn viên",
        type: "item",
        icon: "apps",
        url: "/campus",
        exact: true,
      },
      {
        id: "typeplace",
        title: "Kiểu địa điểm",
        type: "item",
        icon: "apps",
        url: "/typeplace",
        exact: true,
      },
      {
        id: "department",
        title: "Phòng ban",
        type: "item",
        icon: "apps",
        url: "/department",
        exact: true,
      },
      {
        id: "8",
        title: "User",
        type: "item",
        icon: "apps",
        url: "/user",
        exact: true,
      },
      {
        id: "9",
        title: "Vị trí",
        type: "item",
        icon: "apps",
        url: "/place",
        exact: true,
      },
      {
        id: "10",
        title: "Đợt thanh lý",
        type: "item",
        icon: "apps",
        url: "/liquidate",
        exact: true,
      },
      {
        id: "11",
        title: "Đợt kiểm kê",
        type: "item",
        icon: "apps",
        url: "/inventory",
        exact: true,
      },
      {
        id: "12",
        title: "Cơ sở vật chất",
        type: "item",
        icon: "apps",
        url: "/material",
        exact: true,
      },
      {
        id: "kiemke1",
        title: "employees test",
        type: "item",
        icon: "functions",
        url: "/employees",
        exact: true,
      },
    
    ],
  },
  {
    id: "khac",
    title: "KHÁC",
    type: "group",
    children: [
      {
        id: "Authentication",
        title: "Authentication",
        type: "collapse",
        icon: "lock",
        children: [
          {
            id: "Login",
            title: "Login",
            type: "item",
            url: "/login",
            exact: true,
          },
         
        ],
      },
      {
        id: "kiemke",
        title: "Kiểm kê",
        type: "item",
        icon: "functions",
        url: "/test",
        exact: true,
      },
     

      {
        id: "ttts",
        title: "Tình trạng tài sản",
        type: "item",
        icon: "waves",
        url: "/pages/calendarxx",
        exact: true,
      },
      {
        id: "dmsd",
        title: "Định mức sử dụng",
        type: "item",
        icon: "all_inclusive",
        url: "/pages/calendarccc",
        exact: true,
      },
      {
        id: "bc",
        title: "Báo cáo",
        type: "item",
        icon: "poll",
        url: "/pages/about",
        exact: true,
      },
     
    ],
  },
  {
    id: "divider-1",
    type: "divider",
  },
  {
    id: "about",
    title: "ABOUT",
    type: "group",
    children: [
      {
        id: "Team K&P",
        title: "Team K&P",
        type: "link",
        icon: "link",
        url: "https://github.com/PhongMax/asset-management",
        exact: true,
      },
    ],
  },
];

export default navigationConfig;
